title: Math Snake
description: A snake game, but with math and also enemies with guns
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
